plotMassRTsamplewise <- function(xs, how = c("2D", "3D"), ncol = 3,
                   width = ncol * 3, height = nrow * 2.5,
                   maxrow = 5,
                   output = c("x11", "pdf"), fname = "figure_mass_RT_samplewise.pdf") {
## Visualize features in xset objects, i.e., lists of xcmset objects,
## as generated by the web interface running on the metabo

# ( formerly: vizSet visXcmsSet )

# test:
#  source("../Func/plotMassRTsamplewise.R")
#  load('xcmsPeakTable.RData')
#  plotMassRTsamplewise(xset, ncol = 3, how = "2D", output = "pdf")

########################################################################


  # require(xcms)
  # require(scatterplot3d)

  how <- match.arg(how)
  output <- match.arg(output)

  if (class(xs) == "xsAnnotate") xs <- xs@xcmsSet
  xp.orig <- as.data.frame(peaks(xs))
  ## split: one list element for each sample
  xp <- split(xp.orig, xp.orig[,"sample"])
  ## remove those peaks with NA in sn column (and also other columns)
  # xp <- lapply(xp, function(x) x[!is.na(x$sn), c("rt", "mz", "into")])
  
  nrow <-  min(maxrow, ceiling(length(xp) / ncol))
  plotheight <- ifelse(how == "2D", 1, 1.25)
  
  if (output == "x11") {
    x11(width = width, height = height*plotheight)
  } else {
    pdf(file = fname, width = width, height = height*plotheight)
  }
  
  par(mfrow = c(nrow, ncol))

  if (how == "2D") {
    sapply(1:length(xp),
           function(i, xx) {
             x <- xx[[i]]
             plot(x[, "rt"]/60, x[, "mz"], type = "n",
                  xlab = "RT (min)", ylab = "m/z",
                  main = paste(sampnames(xs)[i], ": ", nrow(x),
                    " features", sep = ""))
             abline(v = seq(0, max(x[,"rt"]/60), by = 5), col = "gray",
                    lty = 2)
             points(x[, "rt"]/60, x[, "mz"], col = "blue")
           }, xp)
  } else {
    sapply(1:length(xp),
           function(i, xx) {
             x <- xx[[i]]
             scatterplot3d(x = x[, "rt"], y = x[, "mz"], z = sqrt(x[, "into"]),
                           xlab = "RT (s)", ylab = "", zlab = "sqrt(I)",
                           type = "h", highlight.3d = TRUE,
                           mar=c(5,3,3,0)+0.1, pch = ".", angle = 60,
                           col.grid = "lightblue", tick.marks = FALSE,
                           main = paste(sampnames(xs)[i], ": ", nrow(x),
                             " features", sep = ""))
           }, xp)
  }

  if (output == "pdf")
    dev.off()
  
  invisible()
}

## xsetFile <- "xcmsPeakTable_2.RData"
## ncol <- 3
## how <- "2D"

##  test:
# load(xsetFile)
# plotMassRTsamplewise(xset, ncol = ncol, how = how,
#        output = "pdf", fname = "output.pdf")
